name: Component Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Testdata.txt and export variables
        run: |
          while IFS='=' read -r key value; do
            key=$(echo "$key" | tr -d ' ')
            value=$(echo "$value" | sed -e 's/^ *//g')
            echo "$key=$value" >> $GITHUB_ENV
          done < Testdata.txt

      - name: sleep for 5 seconds
        run: sleep 5s

      - name: Parse report.txt and generate JSON
        run: |
          awk '
            /TEST-CASE-ID:/ {
              split($0, a, ":");
              testcase=a[2];
              gsub(/^[ \t]+/, "", testcase)
            }
            /^"/ {
              comment=$0;
              gsub(/^"|"$/, "", comment)
            }
            /TEST-CASE-RESULT/ {
              split($0, b, ":");
              result=b[2];
              gsub(/^[ \t]+/, "", result)
            }
            END {
              print "{" > "result.json"
              print "  \"testCaseKey\": \"" testcase "\"," >> "result.json"
              print "  \"status\": \"" result "\"," >> "result.json"
              print "  \"environment\": \"FET\"," >> "result.json"
              print "  \"executionTime\": 180000," >> "result.json"
              print "  \"comment\": \"" comment "\"," >> "result.json"
              print "  \"scriptResults\": [" >> "result.json"
              print "    {" >> "result.json"
              print "      \"index\": 0," >> "result.json"
              print "      \"status\": \"" result "\"," >> "result.json"
              print "      \"comment\": \"" comment "\"" >> "result.json"
              print "    }" >> "result.json"
              print "  ]" >> "result.json"
              print "}" >> "result.json"
            }
          ' validation_report.txt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: result.json
          path: result.json
