name: Dynamic Secret Access

on:
  workflow_dispatch:

jobs:
  use_dynamic_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read testdata.txt and map secrets
        id: get_secret_keys
        run: |
          # Extract all keys from testdata.txt
          keys=$(cut -d '=' -f2 Testdata.txt | tr -d '\r')

          # Format keys: lowercase, underscore
          for key in $keys; do
            normalized_key=$(echo "$key" | tr '[:upper:]' '[:lower:]')
            echo "Found key: $normalized_key"
            echo "$normalized_key" >> secret_keys.txt
          done

      - name: Print secret values dynamically
        env:
          # List all potential secrets here manually
          c01_machine: ${{ secrets.C01_machine }}
          service_token: ${{ secrets.SERVICE_TOKEN }}
        run: |
          echo "Reading secret values based on keys in testdata.txt..."
          while read key; do
            value="${!key}"
            if [ -z "$value" ]; then
              echo "Secret for $key not found or not passed in env"
            else
              echo "Value for secret '$key': $value"
            fi
          done < secret_keys.txt
