jobs:
  run-groovy:
    runs-on: ubuntu-latest
    container:
      image: groovy:latest  # Official Groovy image from Docker Hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Groovy script
        run: groovy scripts/JenkinsFile.groovy
